---
- name: containers | networks | read config json
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/_utils/get_config_json.yml"
    apply:
      vars:
        source: "containers | networks"

- name: containers | networks | define entries
  vars:
    current_config: "{{ vyos_active_config_json['container']['network'] | default({}) }}"
  vyos.vyos.vyos_config:
    match: line
    lines: "{{ lookup('template', './config/containers/networks.j2') }}"
