---
fail_fast: false

exclude: ^(docs/variables)

repos:
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint

  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v5.1.3
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: check-added-large-files
        args: [--maxkb=2048]
      - id: check-merge-conflict
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: check-executables-have-shebangs

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.10
    hooks:
      - id: forbid-crlf
      - id: forbid-tabs

  - repo: https://github.com/sirosen/fix-smartquotes
    rev: 0.2.0
    hooks:
      - id: fix-smartquotes
