---
- name: firewall | address-groups | switch to ssh connection
  ansible.builtin.set_fact:
    ansible_connection: ssh

- name: firewall | address-groups | get file contents from remote
  ansible.builtin.slurp:
    src: "{{ item['from_file'] }}"
  with_items:
    - "{{ vyos_firewall_address_groups }}"
  when:
    - item['from_file'] is defined
  register: firewall_remote_address_files

- name: firewall | address-groups | switch to network_cli connection
  ansible.builtin.set_fact:
    ansible_connection: ansible.netcommon.network_cli

- name: firewall | address-groups | store vyos_managed_address_groups
  vars:
    address_group_files: "{{ firewall_remote_address_files['results'] | rejectattr('skipped', 'defined') }}"
  ansible.builtin.set_fact:
    vyos_managed_address_groups: "{{ lookup('template', './config/firewall/address-groups.j2') | from_yaml }}"

- name: firewall | address-groups | get current firewall configuration
  vyos.vyos.vyos_firewall_global:
    config:
    state: gathered
  register: vyos_firewall_current_config

- name: firewall | address-groups | configure
  vars:
    config: "{{ vyos_firewall_current_config['gathered'].copy() }}"
    firewall_groups: "{{ {'address_group': vyos_managed_address_groups} }}"
  vyos.vyos.vyos_firewall_global:
    config: "{{ lookup('template', './config/firewall/firewall-groups.j2') | from_yaml }}"
    state: replaced
