---
- name: firewall | rules | read built-in rules
  ansible.builtin.include_vars:
    file: "{{ role_path }}/files/firewall/builtin_rules.yml"
    name: vyos_firewall_builtin_rules

- name: firewall | rules | read config json
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/_utils/get_config_json.yml"
    apply:
      vars:
        source: "firewall | rules"

- name: firewall | rules | configure ipv4 rulesets
  vars:
    zone_rules: "{{ vyos_firewall_builtin_rules | combine(vyos_firewall_rules) }}"
    current_config: "{{ vyos_active_config_json['firewall']['name'] | default({}) }}"
  vyos.vyos.vyos_config:
    match: line
    lines: "{{ lookup('template', './config/firewall/firewall-rules.j2') | split('\n') }}"
