---
- name: setup
  ansible.builtin.import_tasks:
    file: setup.yml
  tags:
    - always

- name: system
  ansible.builtin.import_tasks:
    file: system/main.yml
  tags:
    - vyos_system

- name: managed files
  ansible.builtin.import_tasks:
    file: managed_files/main.yml
  tags:
    - vyos_managed_files

- name: interfaces
  ansible.builtin.import_tasks:
    file: interfaces/main.yml
  tags:
    - vyos_interfaces

- name: routing
  ansible.builtin.import_tasks:
    file: routing/main.yml
  tags:
    - vyos_routing

- name: nat
  ansible.builtin.import_tasks:
    file: nat/main.yml
  tags:
    - vyos_nat

- name: firewall
  ansible.builtin.import_tasks:
    file: firewall/main.yml
  tags:
    - vyos_firewall

- name: services
  ansible.builtin.import_tasks:
    file: services/main.yml
  tags:
    - vyos_services

- name: dns
  ansible.builtin.import_tasks:
    file: dns/main.yml
  tags:
    - vyos_dns

- name: containers
  ansible.builtin.import_tasks:
    file: containers/main.yml
  tags:
    - vyos_containers

- name: post-config
  ansible.builtin.import_tasks:
    file: post_config/main.yml
  tags:
    - vyos_post_config
