---
- name: 'system | settings'
  ansible.builtin.import_tasks:
    file: settings.yml
  tags:
    - vyos_system_settings

- name: 'system | timezone'
  ansible.builtin.import_tasks:
    file: timezone.yml
  tags:
    - vyos_system_timezone

- name: 'system | syslog'
  ansible.builtin.import_tasks:
    file: syslog.yml
  tags:
    - vyos_system_syslog
  when:
    - vyos_remote_syslog is defined

- name: 'system | users'
  ansible.builtin.import_tasks:
    file: users.yml
  tags:
    - vyos_system_users

- name: 'system | task-scheduler'
  ansible.builtin.import_tasks:
    file: task-scheduler.yml
  tags:
    - vyos_system_task_scheduler
  when:
    - vyos_task_scheduler['tasks'] is defined
