---
# -----------------------
# Services configuration
# -----------------------

vyos_dhcp_server:
  enabled: false
  interfaces: {}

vyos_igmp_proxy:
  enabled: false
  interfaces: {}

vyos_broadcast_relay:
  enabled: false
  rules: []

vyos_mdns_repeater:
  enabled: false
  interfaces: []

vyos_dynamic_dns:
  enabled: false
  interfaces: {}
